// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5_IbkVPZfFfISY-grRiyVwb0nwFmwxwM',
    appId: '1:617935900685:web:2bc65f1b6e1d992eba0544',
    messagingSenderId: '617935900685',
    projectId: 'macromap-connect',
    authDomain: 'macromap-connect.firebaseapp.com',
    storageBucket: 'macromap-connect.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqyjXTzyCvPpAogOh_2klBShhfIA3aCts',
    appId: '1:617935900685:android:37417cdc2cbc2731ba0544',
    messagingSenderId: '617935900685',
    projectId: 'macromap-connect',
    storageBucket: 'macromap-connect.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDio2lrGDe4Tqzy77waW5zvv_X0cDjLZCA',
    appId: '1:617935900685:ios:fa2913bc08d393d5ba0544',
    messagingSenderId: '617935900685',
    projectId: 'macromap-connect',
    storageBucket: 'macromap-connect.firebasestorage.app',
    iosBundleId: 'com.example.macromapConnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDio2lrGDe4Tqzy77waW5zvv_X0cDjLZCA',
    appId: '1:617935900685:ios:fa2913bc08d393d5ba0544',
    messagingSenderId: '617935900685',
    projectId: 'macromap-connect',
    storageBucket: 'macromap-connect.firebasestorage.app',
    iosBundleId: 'com.example.macromapConnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5_IbkVPZfFfISY-grRiyVwb0nwFmwxwM',
    appId: '1:617935900685:web:d82c1f1fd0d9d2f8ba0544',
    messagingSenderId: '617935900685',
    projectId: 'macromap-connect',
    authDomain: 'macromap-connect.firebaseapp.com',
    storageBucket: 'macromap-connect.firebasestorage.app',
  );
}